
[Interface]
PrivateKey = eKjRJ+XrvyRMxN+7qvV+34OHPapTjzgmGKNUBFXOnE8=
Address = 10.8.0.2/24
DNS = 1.1.1.1
MTU = 1420

[Peer]
PublicKey = l4y4vojmO6HKDP21pLgqJ+1Fu7F/IsDf+4PWCxDeQQs=
PresharedKey = 1fgbKy6PbIImXE0bknTe2HsNyp07EF1iLEbpADv/2QY=
AllowedIPs = 0.0.0.0/0,::/0
PersistentKeepalive = 0
Endpoint = 67.170.146.253 :51820